spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice1
    username: root
    password: test123


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081

  spring:
    jpa:
      open-in-view: false

